name: Deploy HTML project to Baota Panel

on:
  push:
    branches:
      - main  # 或者你使用的是 master 分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check formatted output
      run: |
        echo "Username: ${{ secrets.SSH_USERNAME }}x"
        echo "Host: ${{ secrets.SSH_HOST }}x"
        echo "Path: ${{ secrets.DEPLOY_PATH }}x"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"

    - name: Rsync files detail
      run: rsync -avz --delete --exclude '.git/' --exclude '.github/' --exclude 'README.md' --exclude '.gitignore' --exclude='.user.ini' --ignore-errors --partial --verbose --quiet -e "ssh -vvv" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}

